# Generated by Django 6.1 on 2026-08-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('room_type', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField()),
                ('p_address', models.TextField()),
                ('aadhar_ID', models.IntegerField(max_length=12)),
                ('room_number', models.IntegerField(unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('room_type', models.CharField()),
            ],
        ),
    ]
